const cocktailData = [
  {
  idDrink: "17834",
  strDrink: "Abbey Cocktail",
  strDrinkAlternate: null,
  strTags: null,
  strVideo: null,
  strCategory: "Ordinary Drink",
  strIBA: null,
  strAlcoholic: "Alcoholic",
  strGlass: "Cocktail glass",
  strInstructions: "Shake all ingredients (except for the cherry) with ice and strain into a cocktail glass. Top with the cherry and serve.",
  strInstructionsES: null,
  strInstructionsDE: "Alle Zutaten (außer der Kirsche) mit Eis schütteln und in ein Cocktailglas abseihen. Mit der Kirsche verzieren und servieren.",
  strInstructionsFR: null,
  strInstructionsIT: "Shakerare tutti gli ingredienti (tranne la ciliegia) con ghiaccio e filtrare in una coppetta da cocktail. Completare con la ciliegia e servire.",


  strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/mr30ob1582479875.jpg",
  strIngredient1: "Gin",
  strIngredient2: "Orange bitters",
  strIngredient3: "Orange",
  strIngredient4: "Cherry",
  strIngredient5: null,
  strIngredient6: null,
  strIngredient7: null,
  strIngredient8: null,
  strIngredient9: null,
  strIngredient10: null,
  strIngredient11: null,
  strIngredient12: null,
  strIngredient13: null,
  strIngredient14: null,
  strIngredient15: null,
  strMeasure1: "1 1/2 oz ",
  strMeasure2: "1 dash ",
  strMeasure3: "Juice of 1/4 ",
  strMeasure4: "1 ",
  strMeasure5: null,
  strMeasure6: null,
  strMeasure7: null,
  strMeasure8: null,
  strMeasure9: null,
  strMeasure10: null,
  strMeasure11: null,
  strMeasure12: null,
  strMeasure13: null,
  strMeasure14: null,
  strMeasure15: null,
  strImageSource: null,
  strImageAttribution: null,
  strCreativeCommonsConfirmed: "Yes",
  dateModified: "2016-09-02 11:19:28"
  },
  {
  idDrink: "178317",
  strDrink: "Bee's Knees",
  strDrinkAlternate: null,
  strTags: null,
  strVideo: null,
  strCategory: "Cocktail",
  strIBA: null,
  strAlcoholic: "Alcoholic",
  strGlass: "Martini Glass",
  strInstructions: "Shake ingredients with crushed ice Garnish with orange peel ",
  strInstructionsES: null,
  strInstructionsDE: null,
  strInstructionsFR: null,
  strInstructionsIT: "Shakerare gli ingredienti con ghiaccio tritato Guarnire con la scorza d'arancia",


  strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/tx8ne41582475326.jpg",
  strIngredient1: "Gold rum",
  strIngredient2: "Orange Juice",
  strIngredient3: "Lime Juice",
  strIngredient4: "Triple Sec",
  strIngredient5: "",
  strIngredient6: "",
  strIngredient7: "",
  strIngredient8: null,
  strIngredient9: null,
  strIngredient10: null,
  strIngredient11: null,
  strIngredient12: null,
  strIngredient13: null,
  strIngredient14: null,
  strIngredient15: null,
  strMeasure1: "6 cl",
  strMeasure2: "2 cl",
  strMeasure3: "2 cl",
  strMeasure4: "2 jiggers",
  strMeasure5: "",
  strMeasure6: "",
  strMeasure7: "",
  strMeasure8: null,
  strMeasure9: null,
  strMeasure10: null,
  strMeasure11: null,
  strMeasure12: null,
  strMeasure13: null,
  strMeasure14: null,
  strMeasure15: null,
  strImageSource: null,
  strImageAttribution: null,
  strCreativeCommonsConfirmed: "No",
  dateModified: null
  },
  {
  idDrink: "13535",
  strDrink: "Pink Panty Pulldowns",
  strDrinkAlternate: null,
  strTags: null,
  strVideo: null,
  strCategory: "Ordinary Drink",
  strIBA: null,
  strAlcoholic: "Alcoholic",
  strGlass: "Collins Glass",
  strInstructions: "Shake well",
  strInstructionsES: null,
  strInstructionsDE: "Gut schütteln",
  strInstructionsFR: null,
  strInstructionsIT: "Versa in un bicchiere tutti gli ingredienti. Agitare bene",


  strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/squsuy1468926657.jpg",
  strIngredient1: "Sprite",
  strIngredient2: "Pink lemonade",
  strIngredient3: "Vodka",
  strIngredient4: null,
  strIngredient5: null,
  strIngredient6: null,
  strIngredient7: null,
  strIngredient8: null,
  strIngredient9: null,
  strIngredient10: null,
  strIngredient11: null,
  strIngredient12: null,
  strIngredient13: null,
  strIngredient14: null,
  strIngredient15: null,
  strMeasure1: "1 L ",
  strMeasure2: "2 cups ",
  strMeasure3: "2 cups ",
  strMeasure4: null,
  strMeasure5: null,
  strMeasure6: null,
  strMeasure7: null,
  strMeasure8: null,
  strMeasure9: null,
  strMeasure10: null,
  strMeasure11: null,
  strMeasure12: null,
  strMeasure13: null,
  strMeasure14: null,
  strMeasure15: null,
  strImageSource: null,
  strImageAttribution: null,
  strCreativeCommonsConfirmed: "No",
  dateModified: "2016-07-19 12:10:57"
  },
  {
  idDrink: "11011",
  strDrink: "After Supper Cocktail",
  strDrinkAlternate: null,
  strTags: null,
  strVideo: null,
  strCategory: "Ordinary Drink",
  strIBA: null,
  strAlcoholic: "Alcoholic",
  strGlass: "Cocktail glass",
  strInstructions: "Shake all ingredients with ice, strain into a cocktail glass, and serve.",
  strInstructionsES: null,
  strInstructionsDE: "Alle Zutaten mit Eis schütteln, in ein Cocktailglas abseihen und servieren.",
  strInstructionsFR: null,
  strInstructionsIT: "Shakerare tutti gli ingredienti con ghiaccio, filtrare in una coppetta da cocktail e servire.",


  strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/quyxwu1483387610.jpg",
  strIngredient1: "Triple sec",
  strIngredient2: "Apricot brandy",
  strIngredient3: "Lemon juice",
  strIngredient4: null,
  strIngredient5: null,
  strIngredient6: null,
  strIngredient7: null,
  strIngredient8: null,
  strIngredient9: null,
  strIngredient10: null,
  strIngredient11: null,
  strIngredient12: null,
  strIngredient13: null,
  strIngredient14: null,
  strIngredient15: null,
  strMeasure1: "1 oz ",
  strMeasure2: "1 oz ",
  strMeasure3: "1/2 tsp ",
  strMeasure4: null,
  strMeasure5: null,
  strMeasure6: null,
  strMeasure7: null,
  strMeasure8: null,
  strMeasure9: null,
  strMeasure10: null,
  strMeasure11: null,
  strMeasure12: null,
  strMeasure13: null,
  strMeasure14: null,
  strMeasure15: null,
  strImageSource: "https://www.thecocktaildb.com/drink/11011",
  strImageAttribution: "TheCocktailDB.com",
  strCreativeCommonsConfirmed: "Yes",
  dateModified: "2017-01-02 20:06:50"
  },
  {
  idDrink: "17256",
  strDrink: "Martinez 2",
  strDrinkAlternate: null,
  strTags: null,
  strVideo: null,
  strCategory: "Cocktail",
  strIBA: null,
  strAlcoholic: "Alcoholic",
  strGlass: "Cocktail glass",
  strInstructions: "Add all ingredients to a mixing glass and fill with ice. Stir until chilled, and strain into a chilled coupe glass.",
  strInstructionsES: null,
  strInstructionsDE: "Alle Zutaten in ein Mischglas geben und mit Eis füllen. Bis zum Abkühlen umrühren und in ein gekühltes Coupéglas abseihen.",
  strInstructionsFR: null,
  strInstructionsIT: "Aggiungere tutti gli ingredienti in un mixing glass e riempire di ghiaccio, mescolare fino a quando si saranno raffreddati e filtrare in un bicchiere da coupé freddo.",


  strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/fs6kiq1513708455.jpg",
  strIngredient1: "Gin",
  strIngredient2: "Sweet Vermouth",
  strIngredient3: "Maraschino Liqueur",
  strIngredient4: "Angostura Bitters",
  strIngredient5: null,
  strIngredient6: null,
  strIngredient7: null,
  strIngredient8: null,
  strIngredient9: null,
  strIngredient10: null,
  strIngredient11: null,
  strIngredient12: null,
  strIngredient13: null,
  strIngredient14: null,
  strIngredient15: null,
  strMeasure1: "1 1/2 oz",
  strMeasure2: "1 1/2 oz",
  strMeasure3: "1 tsp",
  strMeasure4: "2 dashes",
  strMeasure5: null,
  strMeasure6: null,
  strMeasure7: null,
  strMeasure8: null,
  strMeasure9: null,
  strMeasure10: null,
  strMeasure11: null,
  strMeasure12: null,
  strMeasure13: null,
  strMeasure14: null,
  strMeasure15: null,
  strImageSource: null,
  strImageAttribution: null,
  strCreativeCommonsConfirmed: "No",
  dateModified: "2017-12-19 18:34:15"
  },
  {
  idDrink: "17833",
  strDrink: "A. J.",
  strDrinkAlternate: null,
  strTags: null,
  strVideo: null,
  strCategory: "Ordinary Drink",
  strIBA: null,
  strAlcoholic: "Alcoholic",
  strGlass: "Cocktail glass",
  strInstructions: "Shake ingredients with ice, strain into a cocktail glass, and serve.",
  strInstructionsES: null,
  strInstructionsDE: null,
  strInstructionsFR: null,
  strInstructionsIT: "Shakerare gli ingredienti con ghiaccio, filtrare in una coppetta da cocktail e servire.",


  strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/l74qo91582480316.jpg",
  strIngredient1: "Applejack",
  strIngredient2: "Grapefruit juice",
  strIngredient3: null,
  strIngredient4: null,
  strIngredient5: null,
  strIngredient6: null,
  strIngredient7: null,
  strIngredient8: null,
  strIngredient9: null,
  strIngredient10: null,
  strIngredient11: null,
  strIngredient12: null,
  strIngredient13: null,
  strIngredient14: null,
  strIngredient15: null,
  strMeasure1: "1 1/2 oz ",
  strMeasure2: "1 oz ",
  strMeasure3: null,
  strMeasure4: null,
  strMeasure5: null,
  strMeasure6: null,
  strMeasure7: null,
  strMeasure8: null,
  strMeasure9: null,
  strMeasure10: null,
  strMeasure11: null,
  strMeasure12: null,
  strMeasure13: null,
  strMeasure14: null,
  strMeasure15: null,
  strImageSource: null,
  strImageAttribution: null,
  strCreativeCommonsConfirmed: "Yes",
  dateModified: "2016-09-02 11:16:58"
  },
  {
  idDrink: "11870",
  strDrink: "Orange Oasis",
  strDrinkAlternate: null,
  strTags: null,
  strVideo: null,
  strCategory: "Ordinary Drink",
  strIBA: null,
  strAlcoholic: "Alcoholic",
  strGlass: "Highball glass",
  strInstructions: "Shake brandy, gin, and orange juice with ice and strain into a highball glass over ice cubes. Fill with ginger ale, stir, and serve.",
  strInstructionsES: null,
  strInstructionsDE: "Brandy, Gin und Orangensaft mit Eis schütteln und in ein Highball-Glas über Eiswürfel abseihen. Mit Ginger Ale füllen, umrühren und servieren.",
  strInstructionsFR: null,
  strInstructionsIT: "Shakerare brandy, gin e succo d'arancia con ghiaccio e filtrare in un bicchiere highball con cubetti di ghiaccio. Riempi con ginger ale, mescola e servi.",


  strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/su1olx1582473812.jpg",
  strIngredient1: "Cherry brandy",
  strIngredient2: "Gin",
  strIngredient3: "Orange juice",
  strIngredient4: "Ginger ale",
  strIngredient5: null,
  strIngredient6: null,
  strIngredient7: null,
  strIngredient8: null,
  strIngredient9: null,
  strIngredient10: null,
  strIngredient11: null,
  strIngredient12: null,
  strIngredient13: null,
  strIngredient14: null,
  strIngredient15: null,
  strMeasure1: "1/2 oz ",
  strMeasure2: "1 1/2 oz ",
  strMeasure3: "4 oz ",
  strMeasure4: null,
  strMeasure5: null,
  strMeasure6: null,
  strMeasure7: null,
  strMeasure8: null,
  strMeasure9: null,
  strMeasure10: null,
  strMeasure11: null,
  strMeasure12: null,
  strMeasure13: null,
  strMeasure14: null,
  strMeasure15: null,
  strImageSource: null,
  strImageAttribution: null,
  strCreativeCommonsConfirmed: "Yes",
  dateModified: "2015-09-02 05:25:23"
  },
  {
  idDrink: "12434",
  strDrink: "Valencia Cocktail",
  strDrinkAlternate: null,
  strTags: null,
  strVideo: null,
  strCategory: "Ordinary Drink",
  strIBA: null,
  strAlcoholic: "Alcoholic",
  strGlass: "Cocktail glass",
  strInstructions: "Shake all ingredients with ice, strain into a cocktail glass, and serve.",
  strInstructionsES: null,
  strInstructionsDE: "Alle Zutaten mit Eis schütteln, in ein Cocktailglas abseihen und servieren.",
  strInstructionsFR: null,
  strInstructionsIT: "Shakerare tutti gli ingredienti con ghiaccio, filtrare in una coppetta da cocktail e servire.",


  strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/9myuc11492975640.jpg",
  strIngredient1: "Apricot brandy",
  strIngredient2: "Orange juice",
  strIngredient3: "Orange bitters",
  strIngredient4: null,
  strIngredient5: null,
  strIngredient6: null,
  strIngredient7: null,
  strIngredient8: null,
  strIngredient9: null,
  strIngredient10: null,
  strIngredient11: null,
  strIngredient12: null,
  strIngredient13: null,
  strIngredient14: null,
  strIngredient15: null,
  strMeasure1: "1 1/2 oz ",
  strMeasure2: "1 tblsp ",
  strMeasure3: "2 dashes ",
  strMeasure4: null,
  strMeasure5: null,
  strMeasure6: null,
  strMeasure7: null,
  strMeasure8: null,
  strMeasure9: null,
  strMeasure10: null,
  strMeasure11: null,
  strMeasure12: null,
  strMeasure13: null,
  strMeasure14: null,
  strMeasure15: null,
  strImageSource: null,
  strImageAttribution: null,
  strCreativeCommonsConfirmed: "No",
  dateModified: "2017-04-23 20:27:20"
  },
  {
  idDrink: "11124",
  strDrink: "Boomerang",
  strDrinkAlternate: null,
  strTags: null,
  strVideo: null,
  strCategory: "Ordinary Drink",
  strIBA: null,
  strAlcoholic: "Alcoholic",
  strGlass: "Cocktail glass",
  strInstructions: "In a mixing glass half-filled with ice cubes, combine the gin, vermouth, bitters, and maraschino liqueur. Stir well. Strain into a cocktail glass and garnish with the cherry.",
  strInstructionsES: null,
  strInstructionsDE: "In einem Mischglas, das halb mit Eiswürfeln gefüllt ist, den Gin, Wermut, Bitter und Maraschino-Likör vermengen. Gut umrühren. In ein Cocktailglas abseihen und mit der Kirsche garnieren.",
  strInstructionsFR: null,
  strInstructionsIT: "In un mixing glass riempito a metà con cubetti di ghiaccio, unire il gin, il vermouth, il bitter e il liquore al maraschino.Mescolare bene.Filtrare in una coppetta da cocktail e guarnire con la ciliegia.",


  strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/3m6yz81504389551.jpg",
  strIngredient1: "Gin",
  strIngredient2: "Dry Vermouth",
  strIngredient3: "Bitters",
  strIngredient4: "Maraschino liqueur",
  strIngredient5: "Maraschino cherry",
  strIngredient6: null,
  strIngredient7: null,
  strIngredient8: null,
  strIngredient9: null,
  strIngredient10: null,
  strIngredient11: null,
  strIngredient12: null,
  strIngredient13: null,
  strIngredient14: null,
  strIngredient15: null,
  strMeasure1: "2 oz ",
  strMeasure2: "1/2 oz ",
  strMeasure3: "2 dashes ",
  strMeasure4: "1/2 tsp ",
  strMeasure5: "1 ",
  strMeasure6: null,
  strMeasure7: null,
  strMeasure8: null,
  strMeasure9: null,
  strMeasure10: null,
  strMeasure11: null,
  strMeasure12: null,
  strMeasure13: null,
  strMeasure14: null,
  strMeasure15: null,
  strImageSource: null,
  strImageAttribution: null,
  strCreativeCommonsConfirmed: "No",
  dateModified: "2017-09-02 22:59:12"
  },
  {
  idDrink: "11012",
  strDrink: "Alabama Slammer",
  strDrinkAlternate: null,
  strTags: "Summer",
  strVideo: null,
  strCategory: "Ordinary Drink",
  strIBA: null,
  strAlcoholic: "Alcoholic",
  strGlass: "Highball glass",
  strInstructions: "Pour all ingredients (except for lemon juice) over ice in a highball glass. Stir, add a dash of lemon juice, and serve.",
  strInstructionsES: null,
  strInstructionsDE: "Alle Zutaten (außer Zitronensaft) in einem Highball-Glas über Eis gießen. Umrühren, einen Schuss Zitronensaft hinzufügen und servieren.",
  strInstructionsFR: null,
  strInstructionsIT: "Versare tutti gli ingredienti (tranne il succo di limone) sul ghiaccio in un bicchiere highball.Mescolate, aggiungete un goccio di succo di limone e servite.",


  strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/jntghf1606771886.jpg",
  strIngredient1: "Southern Comfort",
  strIngredient2: "Amaretto",
  strIngredient3: "Sloe gin",
  strIngredient4: "Lemon juice",
  strIngredient5: null,
  strIngredient6: null,
  strIngredient7: null,
  strIngredient8: null,
  strIngredient9: null,
  strIngredient10: null,
  strIngredient11: null,
  strIngredient12: null,
  strIngredient13: null,
  strIngredient14: null,
  strIngredient15: null,
  strMeasure1: "1 oz ",
  strMeasure2: "1 oz ",
  strMeasure3: "1/2 oz ",
  strMeasure4: "1 dash ",
  strMeasure5: null,
  strMeasure6: null,
  strMeasure7: null,
  strMeasure8: null,
  strMeasure9: null,
  strMeasure10: null,
  strMeasure11: null,
  strMeasure12: null,
  strMeasure13: null,
  strMeasure14: null,
  strMeasure15: null,
  strImageSource: "https://www.pxfuel.com/en/free-photo-eplac",
  strImageAttribution: "pxfuel.com",
  strCreativeCommonsConfirmed: "Yes",
  dateModified: "2017-01-02 20:07:27"
  }
  ]

  export default cocktailData